import React from 'react';
import {useNavigate} from 'react-router-dom';
import {Grid} from '@mui/material';
import {styled} from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import StorefrontIcon from '@mui/icons-material/Storefront';
import CustomLabel from 'pages/common/CustomLabel';
const RouteModule = () => {
  const Item = styled(Paper)(({theme}) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    height: 'auto',
    textAlign: 'center',
    color: theme.palette.text.secondary,
    padding: '40px',
    // background: 'white',
    // backgroundColor: isHover ? '#f5f5f5' : 'white',
    borderRadius: '20px',
    boxShadow: '0px 4px 10px -2px rgba(0, 0, 0, 0.07);',
    border: '1px solid #ECECEC',
  }));

  const data = [
    {title: 'Route Master', image: '/assets/images/Routes.svg'},
    {title: 'Auto Generated', image: '/assets/images/AutoGenerated.svg'},
    {title: 'Route List', image: '/assets/images/routelists.svg'},
  ];
  const navigate = useNavigate();
  return (
    <>
      <Grid container spacing={2} sx={{mb: 6}} className='page-header-second'>
        <Grid item xs={9}>
          <CustomLabel labelVal='Route' variantVal='h3-underline' />
        </Grid>
      </Grid>

      <Grid container spacing={6} sx={{padding: '20px', bcakground: 'white'}}>
        {data?.map((el) => {
          return (
            <Grid
              item
              md={2.4}
              sm={4}
              xs={6}
              className='cursor'
              onClick={() => {
                if (el?.title == 'Route Master') {
                  navigate('/master-routes');
                }
                if (el?.title == 'Auto Generated') {
                  navigate('/create-new-route');
                }
                if (el?.title == 'Route List') {
                  navigate('/route-lists/ALL');
                }
              }}
            >
              <Item
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                  flexDirection: 'column',
                  height: '100%',
                }}
              >
                <div
                  style={{
                    background: '#f8f8f8',
                    width: '100px',
                    aspectRatio: '1 / 1',
                    // height: '100px',
                    borderRadius: '50%',
                    // width: '100%',
                    margin: 'auto',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    // position: 'relative',
                  }}
                >
                  {el?.image ? (
                    <img
                      src={el?.image}
                      style={
                        {
                          // position: 'absolute',
                          // marginLeft: '-26px',
                          // marginTop: '20px',
                        }
                      }
                    />
                  ) : (
                    el?.icon
                  )}
                </div>
                <p
                  style={{
                    fontSize: '18px',
                    fontFamily: 'Roboto',
                    color: '#000',
                    fontWeight: '600',
                    fontStyle: 'normal',
                    marginTop: '10px',
                  }}
                >
                  {el?.title}
                </p>
              </Item>
            </Grid>
          );
        })}
      </Grid>
    </>
  );
};

export default RouteModule;
